urls:
  api: 'https://devnet-api.multiversx.com'
  swagger:
    - 'http://localhost:3000'
  redis: '127.0.0.1'
features:
  publicApi:
    enabled: true
    port: 3000
  privateApi:
    enabled: true
    port: 4000
  keepAliveAgent:
    enabled: true
nativeAuth:
  maxExpirySeconds:
  acceptedOrigins:
    - utils.multiversx.com
security:
  admins:
rateLimiterSecret:
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
useCachingInterceptor: false
discover:
  projectId: 1
  signerPemPath: 